---
title: "Cross-Study KRI Report"
date: "`r format(Sys.time(), '%Y-%m-%d %H:%M:%S %Z')`"
output:
  html_document:
    toc: false
    self_contained: true
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  results = 'hide'
)
```

```{r load-packages}
# Load development version
devtools::load_all()

library(gsm.core)
library(dplyr)
library(htmlwidgets)

# Source utility functions
source("util/Sim_Studies.R")
```

```{r simulate-data}
#### Step 1: Simulate Multi-Study Results and Group Data ####

# Simulate multi-study data using Sim_Studies function
sim_data <- Sim_Studies(
  dfMetrics = gsm.core::reportingMetrics,
  n_studies = 10,
  n_sites = 50,
  n_sites_per_study = c(8, 15),
  snapshot_date = as.Date("2025-06-01"),
  seed = 123
)
```

```{r create-summary}
#### Step 2: Create Cross-Study Summary ####

# Create the cross-study summary data
dfCrossStudySummary <- SummarizeCrossStudy(
  dfResults = sim_data$dfResults,
  dfGroups = sim_data$dfGroups
)
```

```{r create-widget, results='asis'}
#### Step 3: Create Cross-Study Widgets ####
cross_study_widget <- Widget_CrossStudyRiskScore(
  dfResults = sim_data$dfResults,
  dfMetrics = gsm.core::reportingMetrics,
  dfGroups = sim_data$dfGroups
)

# Display the widget directly in the document
cross_study_widget
```
