#' Report Flag Changes
#'
#' Generate an HTML summary of newly changed risk flags between snapshots.
#'
#' This function compares the current and previous snapshot for each group/metric and lists all changes in flag status, including the direction and magnitude of change. It provides a detailed breakdown for each change, including the group, metric, flag transition, score and metric changes, and numerator/denominator details. Optionally, if `GroupLabel` or `MetricLabel` columns are present, they will be used for display; otherwise, `GroupID` and `MetricID` are used.
#'
#' @param dfResults A data.frame generated by gsm.reporting::CalculateChange(), containing both current and previous snapshot columns. Optionally, may include custom `GroupLabel` and `MetricLabel` columns for display.
#'
#' @return HTML (character) containing a nested unordered list of newly changed flags, grouped by absolute flag value and color-coded. Each entry includes the flag transition, score/metric/numerator/denominator changes, and snapshot details.
#'
#' @details
#'
#' - Only rows where the flag value has changed (including NA transitions) are included.
#' - Rows where the flag went from NA to green (0) are excluded.
#' - Results are grouped and color-coded by the absolute value of the new flag (red, amber, green).
#' - For each change, the function displays:
#'   - Group and metric (using labels if available)
#'   - Flag transition (with icon)
#'   - Score and metric changes (\eqn{\Delta} Score, \eqn{\Delta} Metric, etc.`)
#'   - Previous and current snapshot details (flag, score, rate, numerator/denominator)
#'
#' @export


Report_FlagChange <- function(dfResults) {

  # Check that dfResults contains required columns
  required_cols <- c(
    "StudyID", "GroupLevel", "GroupID", "MetricID", "Flag_Change", "SnapshotDate",
    "Flag", "Flag_Previous", "Score_Change", "Score_Previous", "Score",
    "Numerator_Previous", "Denominator_Previous", "Metric_Previous",
    "Numerator", "Denominator", "Metric"
  )
  missing_cols <- setdiff(required_cols, colnames(dfResults))
  if (length(missing_cols) > 0) {
    cat(paste("Missing delta columns in dfResults:", paste(missing_cols, collapse=", "), ". Not rendering list of newly changed flags."))
    return(NULL)
  }
  # if GroupLabel/MetricLabel columns are missing use GroupID/MetricID
  if (!"GroupLabel" %in% colnames(dfResults)) {
    dfResults$GroupLabel <- dfResults$GroupID
  }
  if (!"MetricLabel" %in% colnames(dfResults)) {
    dfResults$MetricLabel <- dfResults$MetricID
  }

  # Only show Risk Signals where flag has changed from previous snapshot
  changed <- dfResults %>%
  dplyr::filter(
    (is.na(Flag) & !is.na(Flag_Previous)) |
    (!is.na(Flag) & is.na(Flag_Previous)) |
    (Flag != Flag_Previous)
  ) %>%
  # Drop rows where flag went from NA -> Green
  filter(!(is.na(Flag_Previous) & Flag==0)) %>%
  # Sort by previous flag and then current flag
  dplyr::arrange(dplyr::desc(abs(Flag_Previous))) %>%
  dplyr::arrange(dplyr::desc(abs(Flag))) %>%
  mutate(absolute_flag= abs(Flag))

  # Split by absolute_flag and generate separate lists
  cat(glue::glue("<h3>Flags Changes</h3>"))
  cat(glue::glue("<p>Found {nrow(changed)} Risk Signals where the Flag Value Changed. In the list below, click items with +/- to show/hide details. <a class='change-expand-all'>Click here</a> to expand all, or <a class='change-collapse-all'>click here</a> to collapse all.</p>"))
  cat('<ul class="flag-change-list">')
  abs_flag_levels <- sort(unique(changed$absolute_flag), decreasing = TRUE)
  abs_flag_colors <- list(
    "2"="<span style='color:red;font-weight:bold'>red</span>",
    "1"="<span style='color:#FEAA02;font-weight:bold'>amber</span>",
    "0"="<span style='color:green;font-weight:bold'>green</span>"
  )
  rArrow <- "<span style='font-size:1.2em;'>&#8594;</span>"
  for (af in abs_flag_levels) {
    changed_af <- changed %>% dplyr::filter(absolute_flag == af)
    color <- abs_flag_colors[[as.character(af)]]
    # Expand red flags by default, others minimized
    nested_class <- if (color == "red") {
      "flag-change-nested flag-change-expanded"
    } else {
      "flag-change-nested"
    }
    if (nrow(changed_af) > 0) {
        cat(glue::glue("<li class='flag-change-parent'>Found {nrow(changed_af)} new {color} flags <ul class='{nested_class}'>"))
        apply(changed_af, 1, function(row) {
            group = glue("{row['GroupLabel']}")
            metric = glue("{row['MetricLabel']}")
            flag <- glue::glue("{Report_FormatFlag(as.numeric(row['Flag']))}")
            prev_flag <- glue::glue("{Report_FormatFlag(as.numeric(row['Flag_Previous']))}")
            flagChange = glue::glue("{prev_flag} {rArrow} {flag}")
            previousSnap = glue::glue("{row['SnapshotDate_Previous']} | {prev_flag} | Score: {row['Score_Previous']} | Rate: {row['Numerator_Previous']} / {row['Denominator_Previous']} ({round(as.numeric(row['Metric_Previous']), 2)})")
            currentSnap = glue::glue("{row['SnapshotDate']} | {flag} | Score: {row['Score']} | Rate: {row['Numerator']} / {row['Denominator']} ({round(as.numeric(row['Metric']), 2)})")
            delta = glue::glue(
              "\\(\\Delta\\) Score: {sprintf('%+.2f', as.numeric(row['Score_Change']))} | " ,
              "\\(\\Delta\\) Metric: {sprintf('%+.2f', as.numeric(row['Metric_Change']))} | ",
              "\\(\\Delta\\) Numerator: {sprintf('%+d', as.integer(row['Numerator_Change']))} | ",
              "\\(\\Delta\\) Denominator: {sprintf('%+d', as.integer(row['Denominator_Change']))}"
            )
            cat(glue::glue("<li class='flag-change-item'>{group} | {metric} | {flagChange}<ul class='flag-change-details'>"))
            cat(glue::glue("<li>Current Snapshot: {currentSnap}</li>"))
            cat(glue::glue("<li>Previous Snapshot: {previousSnap}</li>"))
            cat(glue::glue("<li>{delta}</li>"))
            cat("</ul></li>")
        })
        cat("</ul></li>")
    }
  }
  cat('</ul>')
}
