#' Report Flag Changes
#'
#' Create an HTML list of newly changed flags using the data generated by CalculateChange().
#'
#' @param dfResults A data.frame generated by gsm.reporting::CalculateChange().
#' @return A character string containing an HTML unordered list of newly changed flags.
#' @export

Report_FlagChange <- function(dfResults) {
  required_cols <- c("StudyID", "GroupLevel", "GroupID", "MetricID", "Flag_Change", "SnapshotDate")
  missing_cols <- setdiff(required_cols, colnames(dfResults))
  if (length(missing_cols) > 0) {
    warning(paste("Missing delta columns in dfResults:", paste(missing_cols, collapse=", "), ". Not rendering list of newly changed flags."))
    return(NULL)
  }

  changed <- dfResults %>% 
  # Keep Rows where flag has changed
  dplyr::filter(
    (is.na(Flag) & !is.na(Flag_Previous)) |
    (!is.na(Flag) & is.na(Flag_Previous)) |
    (Flag != Flag_Previous)
  ) %>% 
  # Drop rows where flag went from NA -> Green
  filter(!(is.na(Flag_Previous) & Flag==0)) %>%
  # Sort by previous flag and then flag 
  dplyr::arrange(dplyr::desc(abs(Flag_Previous))) %>%
  dplyr::arrange(dplyr::desc(abs(Flag))) %>%
  mutate(absolute_flag= abs(Flag))

  if (nrow(changed) == 0) {
    cat("<ul><li>No newly changed flags in the most recent snapshot.</li></ul>")
    return(NULL)
  }

  # Split by absolute_flag and generate separate lists
  cat(glue::glue("<h3>New Flags</h3>"))
  cat('<ul>')
  abs_flag_levels <- sort(unique(changed$absolute_flag), decreasing = TRUE)
  abs_flag_colors <- list("2"="red", "1"="amber", "0"="green")
  rArrow <- "<span style='font-size:1.2em;'>&#8594;</span>"
  for (af in abs_flag_levels) {
    changed_af <- changed %>% dplyr::filter(absolute_flag == af)
    color <- abs_flag_colors[[as.character(af)]]
    if (nrow(changed_af) > 0) {
        cat(glue::glue("<li>Found {nrow(changed_af)} new <span style='color:{color};font-weight:bold'>{color}</span> flags <ul>"))
        apply(changed_af, 1, function(row) {
            group = glue("{row['GroupID']}")
            metric = glue("{row['MetricID']}")
            flag <- glue::glue("{Report_FormatFlag(as.numeric(row['Flag']))}")
            prev_flag <- glue::glue("{Report_FormatFlag(as.numeric(row['Flag_Previous']))}")
            flagChange = glue::glue("{prev_flag} {rArrow} {flag} | ΔScore: {round(as.numeric(row['Score_Change']), 2)} ({row['Score_Previous']} {rArrow} {row['Score']})")
            previousSnap = glue::glue("{row['PrevSnapshotDate']} | {prev_flag} | Score: {row['Score_Previous']} | Rate: {row['Numerator_Previous']} / {row['Denominator_Previous']} (", ifelse(!is.na(row['Rate_Previous']), round(as.numeric(row['Rate_Previous']), 2), "NA"), ")")
            currentSnap = glue::glue("{row['SnapshotDate']} | {flag} | Score: {row['Score']} | Rate: {row['Numerator']} / {row['Denominator']} (", ifelse(!is.na(row['Rate']), round(as.numeric(row['Rate']), 2), "NA"), ")")
            cat(glue::glue("<li>{row['GroupID']} | {row['MetricID']} | {flagChange}<ul>"))
            cat(glue::glue("<li>Previous: {previousSnap}</li>"))
            cat(glue::glue("<li>Current: {currentSnap}</li>"))
            cat("</ul></li>")
        })
        cat("</ul></li>")
    }
  }
  cat('</ul>')
}
