on:
  release:
    types: [published]
  pull_request:
    branches: dev
  workflow_dispatch:

name: qualification-report

jobs:
  qualification-report:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.3'
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-tinytex@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: qualification report trigger
        uses: peter-evans/repository-dispatch@main
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          repository: Gilead-BioStats/gsm.qc
          event-type: [qualification]
          client-payload: '{
          "GH_TOKEN": "${{ secrets.GITHUB_TOKEN }}",
          "repository": "${{ github.repository }}",
          "release_tag": "${{ github.ref_name }}",
          }'
